services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: proxy-manager
    restart: always
    ports:
      - "80:80" #Http
      - "81:81" #administracion de la API
      - "443:443" #Https
    volumes:
      - ./npm_data:/data
      - ./npm_letsencrypt:/etc/letsencrypt
    networks:
      - red-cba

  servidor-bd:
    image: mysql:8.0
    container_name: servidor-bd
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - red-cba

  app-backend:
    image: spl4shsc4r/proyecto-app-flask:latest

    container_name: app-backend

    ports:
      - "5050:5050"

    depends_on:
      - servidor-bd

    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

    networks:
      - red-cba

networks:
  red-cba:
    name: red-cba-ejemplo

volumes:
  mysql_data: