  services:
    nginx-proxy-manager:
      image: 'jc21/nginx-proxy-manager:latest'
      container_name: proxy-manager
      restart: always
      ports:
        - "80:80"
        - "81:81"
        - "443:443"
      volumes:
        - ./npm_data:/data
        - ./npm_letsencrypt:/etc/letsencrypt
      depends_on:
        - app-backend
      networks:
        - red-cba

    servidor-bd:
      image: mysql:8.0
      container_name: servidor-bd-ejemplo
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}
      volumes:
        - mysql-data:/var/lib/mysql
      networks:
        - red-cba
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        timeout: 5s
        retries: 3

    app-backend:
      image: morenoalexis13724-sudo/link-de-despliegue:latest
      container_name: app-backend-ejemplo
      ports:
        - "5050:5050"
      environment:
        FLASK_ENV: development
        DB_HOST: ${DB_HOST}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
      networks:
        - red-cba
      depends_on:
        servidor-bd:
          condition: service_healthy

    uptime-kuma:
      image: louislam/uptime-kuma:1
      container_name: uptime-kuma
      restart: always
      ports:
        - "3001:3001"
      volumes:
        - uptime-kuma-data:/app/data
      networks:
        - red-cba


    dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: always
    volumes:
      -/var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    networks:
    - red-cba



  networks:
    red-cba:
      name: red-cba-ejemplo

  volumes:
    mysql-data:
      name: mysql-data
    uptime-kuma-data:
      name: uptime-kuma-data
