CREATE TABLE IF NOT EXISTS aprendices (
    id INT NOT NULL AUTO_INCREMENT,
    nombre_completo VARCHAR(100) NOT NULL,
    numero_documento VARCHAR(20) NOT NULL,
    ficha VARCHAR(20) NOT NULL,
    creado_en TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;